Revert update to 4.1.2 since it didn't work well, there was the following error in the flexible client
ERROR: Unable to resolve dependency for ':DocumentScanner@debug/compileClasspath': Failed to transform opencv-4.3.0-SNAPSHOT.aar (com.genexus:opencv:4.3.0-SNAPSHOT:20200408.193058-1) to match attributes {artifactType=jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=integration, org.gradle.usage=java-api}.